#!/bin/zsh
RANDOOP_PATH="/Users/felix/Desktop/legacy-code-vortrag/randoop-4.1.1"
RANDOOP_JAR="/Users/felix/Desktop/legacy-code-vortrag/randoop-4.1.1/randoop-all-4.1.1.jar"
echo $RANDOOP_PATH
echo $RANDOOP_JAR
TARGET_CLASSES="/Users/felix/Desktop/legacy-code-vortrag/legacyExample/legacyExample/target/classes"
TARGET_DEPENDENCIES="/Users/felix/Desktop/legacy-code-vortrag/legacyExample/legacyExample/target/dependency/*"
CLASSPATH=$TARGET_CLASSES:$RANDOOP_JAR:$TARGET_DEPENDENCIES
echo $CLASSPATH

DIRECTORY="/Users/felix/Desktop/legacy-code-vortrag/legacyExample/legacyExample/target/dependency"

if [ ! -d "$DIRECTORY" ]; then
	mvn dependency:copy-dependencies
fi

cd src/test/java

BEGIN=$(date +%s)

java -Xmx8000m -classpath $CLASSPATH randoop.main.Main gentests --testclass=de.ch4inl3ss.aktivitaet.Aktivitaet --junit-package-name=de.ch4inl3ss.aktivitaet

END=$(date +%s)
echo "Der Vorgang dauerte $((END-BEGIN)) Sekunden"