/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 21 13:37:35 GMT 2019
 */

package de.ch4inl3ss.randomsample;

import org.junit.Test;
import static org.junit.Assert.*;
import de.ch4inl3ss.randomsample.RandomDataExample;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RandomDataExample_ESTest extends RandomDataExample_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RandomDataExample randomDataExample0 = new RandomDataExample();
      String string0 = randomDataExample0.someLogicHere((-2562));
      assertEquals("nicht 10", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RandomDataExample randomDataExample0 = new RandomDataExample();
      String string0 = randomDataExample0.someLogicHere(10);
      assertEquals("10", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RandomDataExample randomDataExample0 = new RandomDataExample();
      String string0 = randomDataExample0.someLogicHere(569);
      assertEquals("nicht 10", string0);
  }
}
