/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 21 13:40:32 GMT 2019
 */

package de.ch4inl3ss.model;

import org.junit.Test;
import static org.junit.Assert.*;
import de.ch4inl3ss.model.State;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class State_ESTest extends State_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      State[] stateArray0 = State.values();
      assertNotNull(stateArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      State state0 = State.valueOf("COMPLEX");
      assertEquals("complex", state0.getState());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      State state0 = State.DATABASE;
      String string0 = state0.getState();
      assertEquals("database", string0);
  }
}
